### ISSUE TITLE
Segmentation fault on makefont

### ISSUE THREAD

**Issue by rougier** [rougier/freetype-gl#101]
I've a problem with the makefont, I suspect this [commit](https://github.com/rougier/freetype-gl/commit/0bf8a4618283708041f664c7a0fe5cd989a98dcd#diff-6d39457f541237373326fd725d00cfb7) to be responsible.

Dependencies to GLFW have been  removed but at some point in the font generation, the atlas is uploaded to the texture and it seg faults. Does anyone got the same behavior ?

**Comment by adrianbroher** [comment]
> I've a problem with the makefont, I suspect this commit to be responsible.

It's must be that commit, there were no other changes on `makefont` the last time. `makefont` calls `texture_font_load_glyphs` which in turn calls `texture_atlas_upload` (texture-font.c:657).  Can you comment out that line to confirm if it is the cause of the segfault?

> Does anyone got the same behavior ?

It's not reproducible for me obviously.

**Comment by rougier** [comment]
Yes, I identified the same faulty line. How is that it is not reproducible for  you since there is no available GL context when texture_atlas_upload is called, no ?

**Comment by adrianbroher** [comment]
> How is that it is not reproducible for you since there is no available GL context when texture_atlas_upload is called, no ?

The application just works as expected and I don't know why.  Maybe the OpenGL context of the window manager 'bleeds through'.

Anyway.  How should we fix this? Undoing the commits?  I would prefer remove said line and let the client application call `texture_atlas_upload` instead.

**Comment by adrianbroher** [comment]
>  I would prefer remove said line and let the client application call texture_atlas_upload instead.

It seems like this is already done in the harfbuzz variant.

**Comment by rougier** [comment]
Yes, for making the font, there is no need to to upload the texture and it is better to let the client do that.
