### ISSUE TITLE
`ansi` does not render correct output.

### ISSUE THREAD

**Issue by adrianbroher** [rougier/freetype-gl#102]
When playing around with implementing an automated test function I realized that the current `ansi` demo doesn't render the text I would expect.  According to the reference image located at `doc/images/ansi.png` and the rendering output of the gnome terminal there are several issues with the current result:

* Lines containing only a newline character only don't add a new line.
* Bold text is not rendered properly.
* Italic text ist not rendered properly.
* There is some spaces where they shouldn't be in the color cube.

I attached the different images for comparison:

Image from the documentation:

![ansi-ref](https://cloud.githubusercontent.com/assets/84891/13259229/cc69bb28-da56-11e5-8f08-77c5f37da5b4.png)

Image rendered by the demo:
![ansi-current](https://cloud.githubusercontent.com/assets/84891/13259295/0ac598f6-da57-11e5-96fc-49810369cf4f.png)

Image rendered by the gnome terminal (please ignore the cat statement):
![ansi-from-gnome-terminal](https://cloud.githubusercontent.com/assets/84891/13259412/86dcb12c-da57-11e5-96ca-3af52c2f9529.png)

**Comment by rougier** [comment]
Yes, confirmed. I'm tracking down the bug. Is that possible the uft8_xxx functions do not work for a single `\n`?

**Comment by adrianbroher** [comment]
That was my first idea too, but checking out a pre-utf8 version (b0166992) and doing a clean build still resulted in the same wrong rendering.

**Comment by rougier** [comment]
I guess it's a work for `git bisect` but I've never managed to use it...

If you add a simple space for each single newline, then rendering is ok. So this might very a bound problem somewhere (<= instead of <)

**Comment by adrianbroher** [comment]
> I guess it's a work for git bisect but I've never managed to use it...

In theory yes but for this bug it isn't the case, unless you can find a 'working' commit.  I didn't find one yet.

**Comment by rougier** [comment]
From my investigation, the problem might in [line 351](https://github.com/rougier/freetype-gl/blob/master/text-buffer.c#L351) in text-buffer. We return without updating the cursor position.

**Comment by adrianbroher** [comment]
According to `text_buffer_finish_line` doc the last parameter indicates if the pen should advance one line or not.  However the code doing this on [line 257](https://github.com/rougier/freetype-gl/blob/master/text-buffer.c#L257) refers to self->line_descender, which is 0 for "\n" strings.  Is line_descender even the correct variable?  A descender is something else then a the line leading.  AFAIK we store the leading in the texture_font_t height attribute.

**Comment by rougier** [comment]
But just after that, there is `self->line_descender = 0`. Does not make much sense to me. Do you know who coded this function ? We should better ask him (I hope it's not me).

**Comment by rougier** [comment]
It seems the self->line_descender is taken from the markup.

**Comment by bobkocisko** [comment]
I coded text_buffer_finish_line but the lines in question I simply
extracted from the previous code that was inside line 351
<https://github.com/rougier/freetype-gl/blob/master/text-buffer.c#L351> and
added the advancePen logic.   Can't say who coded that before.

**Comment by rougier** [comment]
I think I've the explanation. `self->line_descender`/`self->line_ascender` are reset after each newline and are kept up to date with the actual markup ascender/descender. Problem is that if a line is made of a single `\n`, `self->line_descender`/`self->line_ascender are not updated (line 351, update happens just after). One quick fix is to explicitely add `pen->y -= (markup->font->ascender - self->line_ascender);` after line 352.

**Comment by adrianbroher** [comment]
> One quick fix is to explicitely add pen->y -= (markup->font->ascender - self->line_ascender); after line 352.

That didn't work, it introduced new lines between every actual existing new line.  But I think I've  fixed the missing newlines issue by putting the check for newlines after setting the line ascender and descender.

**Comment by rougier** [comment]
Yes, fixed for me.
