### ISSUE TITLE
subpixel demo: blank screen (but two lines)

### ISSUE THREAD

**Issue by rougier** [rougier/freetype-gl#103]
The subpixel demos does not work anymore on my system. Is that only me ?
(no text displayed, only the two surroundings line are drawn)

**Comment by adrianbroher** [comment]
Yes, I can confirm this.

**Comment by adrianbroher** [comment]
Bug was introduced in commit 28b0dd5a.  Seems like I forgot to add the `texture_atlas_upload` call in that demo.  I didn't test that demo, because subpixel hinting is disabled on Fedora in the standard FreeType package for patent reasons.
