### ISSUE TITLE
Sections of font missing at different sizes

### ISSUE THREAD

**Issue by boorishpea** [rougier/freetype-gl#104]
Hello,

Please see this screen shot taken from running the font demo

http://s27.postimg.org/t0bsqtwpf/font.png

Is there anything that I can do to fix the problem with white lines appearing to strike through the text at various sizes? also some letters seem to join.

Thanks

**Comment by rougier** [comment]
It seems the font you're using is "pixelated". What is the font name ?

**Comment by boorishpea** [comment]
Unifont - http://unifoundry.com/unifont.html

**Comment by boorishpea** [comment]
The "fontstash" library doesnt do this but is obviously written differently, I don't know what the differences are, and this library seems to have more active contributors.

**Comment by boorishpea** [comment]
Is there anything that I can try to fix this? I really need to use this font.

**Comment by rougier** [comment]
Sorry to not have answered you sooner. The font you're using is a bit "weird" in the sense that it is pixelated (on purpose) and I'm not sure if the problem you mentioned is related to that or not.

Can you test it using that atb-agg.c demo ?

**Comment by boorishpea** [comment]
The font doesn't appear at all in the atb-agg demo, it's just a black background with the properties editor.

**Comment by rougier** [comment]
Only with this font or with any font ?

**Comment by boorishpea** [comment]
only this font

**Comment by rougier** [comment]
Ok. I need to test it on my side. I'm quite busy right now but I'll try in the newt few days.
Don't hesitate to ping me here for update.

**Comment by boorishpea** [comment]
Thank you!

**Comment by boorishpea** [comment]
Sorry it wasn't loading the file, but it's loading now. It does look easier on the eye in this demo (maybe because of white on black) however there still appears to be the problem with the solid strikethrough, the default font size is 16 but at 14 and 13 you can clearly see this problem.

**Comment by boorishpea** [comment]
With hinting turned off the strikethrough seems to disappear
