### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by boorishpea** [rougier/freetype-gl#105]
I use unifont from http://unifoundry.com/unifont.html

When I use the FTGL library it supports all the characters, but has a major performance problem, which is why I have moved over to this library.

All the characters that I am trying to display show up as ?question marks

examples http://www.ltg.ed.ac.uk/~richard/unicode-sample.html

1) Is this already supported by I need to enable a flag or something?
2) will unicode support be added?
3) do I just need to convert to utf or something?

**Comment by rougier** [comment]
Unicode is supported but it also depends on what character are available in your font.
You can have a look at the demo-markup example.

**Comment by boorishpea** [comment]
I see in that demo there is a property set called lang .. "lang=ja"
the font that I am using tries to contain a glyph for every codepoint in unicode
how do I enable all languages "lang=all" doesnt seem to work

**Comment by rougier** [comment]
The line `char *f_japanese = match_description("Droid Sans:size=18:lang=ja");` tells font config to try to find a Droid Sans Font for the Japanese language. But I'm not sure there exists a font containing all the glyphs.

**Comment by boorishpea** [comment]
unifont from http://unifoundry.com/unifont.html tries

**Comment by boorishpea** [comment]
http://unifoundry.com/pub/unifont-8.0.01/unifont-8.0.01.bmp

**Comment by rougier** [comment]
Impressive.... 
In the meantime, markup demo does not work on my side. 
@adrianbroher Do you confirm the problem on your side ?

**Comment by boorishpea** [comment]
yes

**Comment by adrianbroher** [comment]
> Do you confirm the problem on your side ?

No, I can't confirm it.

![./markup demo screenshot](https://cloud.githubusercontent.com/assets/84891/13897886/220d9cac-edc1-11e5-9bfb-0360bc879de7.png)

**Comment by adrianbroher** [comment]
@boorishpea Which variant of the unifont do you use?

**Comment by boorishpea** [comment]
The Standard Unifont TTF Download: unifont-8.0.01.ttf (12 Mbytes)

**Comment by boorishpea** [comment]
did you have any luck getting it to work? I just get question marks replacing unicode text from this font

**Comment by adrianbroher** [comment]
> did you have any luck getting it to work?

It works as expected for me.

![markup](https://cloud.githubusercontent.com/assets/84891/14391923/04288fd6-fdbf-11e5-8d8c-698be4772c12.png)

I placed the `unifont-8.0.01.ttf` into the `fonts` directory.  The changes are described in the attached patch file:


[markup-unifont.txt](https://github.com/rougier/freetype-gl/files/210582/markup-unifont.txt)

**Comment by boorishpea** [comment]
I see that you are setting the font family every time you want to use a specific language, is there any way to build an atlas for all languages so that any character can be used or is that going to cause performance issues?

**Comment by boorishpea** [comment]
does font config work on windows? I am having problems compiling the markup demo

**Comment by boorishpea** [comment]
I am getting

Using GLEW 1.9.0
"font_manager_get_from_description" not implemented yet.
Houston, we've got a problem !

**Comment by rougier** [comment]
I think font-config (fc) does not work on windows.

**Comment by boorishpea** [comment]
can i use this markup demo without?

**Comment by boorishpea** [comment]
if I use the atb-agg.c demo I get question marks where ever I put unicode

**Comment by rougier** [comment]
If font-config is not available, you have to give the filename to the font in the markup

**Comment by boorishpea** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17771678/14405723/c2b70234-fe8c-11e5-80cd-a423c84265e5.png)

**Comment by boorishpea** [comment]
char *f_normal = "fonts/unifont-8.0.01.ttf";
	char *f_bold = "fonts/unifont-8.0.01.ttf";
	char *f_italic = "fonts/unifont-8.0.01.ttf";
	char *f_japanese = "fonts/unifont-8.0.01.ttf";
	char *f_math = "fonts/unifont-8.0.01.ttf";

	markup_t normal = {
		.family = f_normal,
		.size = 24.0,.bold = 0,.italic = 0,
		.rise = 0.0,.spacing = 0.0,.gamma = 2.,
		.foreground_color = white,.background_color = none,
		.underline = 0,.underline_color = white,
		.overline = 0,.overline_color = white,
		.strikethrough = 0,.strikethrough_color = white,
		.font = 0,
	};
	markup_t highlight = normal; highlight.background_color = grey;
	markup_t reverse = normal; reverse.foreground_color = black;
	reverse.background_color = white;
	reverse.gamma = 1.0;
	markup_t overline = normal; overline.overline = 1;
	markup_t underline = normal; underline.underline = 1;
	markup_t small = normal; small.size = 10.0;
	markup_t big = normal; big.size = 48.0;
	big.italic = 1;
	big.foreground_color = yellow;
	markup_t bold = normal; bold.bold = 1; bold.family = f_bold;
	markup_t italic = normal; italic.italic = 1; italic.family = f_italic;
	markup_t japanese = normal; japanese.family = f_japanese;
	japanese.size = 18.0;
	markup_t math = normal; math.family = f_math;


	vec2 pen = { { 20, 200 } };
	text_buffer_printf(buffer, &pen,
		&underline, "The",
		&normal, " Quick",
		&big, " brown ",
		&reverse, " fox \n",
		&italic, "jumps over ",
		&bold, "the lazy ",
		&normal, "dog.\n",
		&small, "Now is the time for all good men "
		"to come to the aid of the party.\n",
		&italic, "Ég get etið gler án þess að meiða mig.\n",
		&japanese, "私はガラスを食べられます。 それは私を傷つけません\n",
		&math, "ℕ ⊆ ℤ ⊂ ℚ ⊂ ℝ ⊂ ℂ",
		NULL);

**Comment by wmamrak** [comment]
Is the encoding of the file correct?

**Comment by boorishpea** [comment]
encoding is "Unicode - (UTF-8 with signature) - Codepage 65001"

**Comment by boorishpea** [comment]
I guess I have to look at creating a minimal, complete and verifiable example

**Comment by boorishpea** [comment]
[markup.c.txt](https://github.com/rougier/freetype-gl/files/211922/markup.c.txt)

**Comment by boorishpea** [comment]
can you recreate the problem with that example? for me this produces the screenshot I showed above where the Unicode characters are shown as question marks.

**Comment by adrianbroher** [comment]
@boorishpea 

While searching the internet for something  unrelated I came across [this SO question](http://stackoverflow.com/questions/688760/how-to-create-a-utf-8-string-literal-in-visual-c-2008).  It seems like starting with VS 2005 and more recent the compiler narrows the content to string literals to the locale when you store the source file as UTF-8 leading BOM (MS terminology: UTF-8 with signature).

To fix your problems you can either:

1. Store the source code file as UTF-8 without BOM.  The compiler will not do any *smart* processing on the literals as far as I understood.
2. Use numeric escape sequences (\xhh) to encode literals with a codepoint greater than U+007F.

**Comment by boorishpea** [comment]
I tried with "Unicode - (UTF-8 _without_ signature) - Codepage 65001" and it worked! Thank you!
