### ISSUE TITLE
Bug fix available for edtaa3func.c

### ISSUE THREAD

**Issue by stegu** [rougier/freetype-gl#110]
I notice that my function for anti-aliased distance transform which is included in this project is an older version that has a small bug which I fixed in 2014. The bug is not fatal, but it reduces the accuracy of some small details, and the fix is just a small change to one line of code. My updated version is in this archive:

http://www.itn.liu.se/~stegu/aadist/texture_creation.zip

The affected files are "edtaa3func.c" and "edtaa3func.h".

**Comment by rougier** [comment]
Hi Stefan,

Thanks for the information. Could you make a PR ?

**Comment by adrianbroher** [comment]
> Thanks for the information. Could you make a PR ?

Np, I will do that.

@stegu 

> The affected files are "edtaa3func.c" and "edtaa3func.h".

Please correct me when I'm wrong, but the distribution you linked doesn't contain any `edtaa3func.h` at all.  Also I don't see any API change so it's probably only the updated license banner, right?

Anyway thanks a lot for pointing out the updated/corrected version.

**Comment by stegu** [comment]
Ok, sorry about the missing header file. It hasn't changed. However, it's
not just a license change. There is a bug fix in the .c file that changes
one line of code for the gradient computation. A diff will show it clearly.

**Comment by adrianbroher** [comment]
> There is a bug fix in the .c file that changes one line of code for the gradient computation.

Sorry for being not clear: I was talking about `edtaa3func.h`.  The bugfix is about calculating `gy` in `edtaa3func.c`.

**Comment by adrianbroher** [comment]
I also have the subtle feel that this bugfix is related to #97.

**Comment by stegu** [comment]
My feeling is the same, but I probably can't find the time to verify it in
the near future. All I can say is that the slight errors demonstrated in
that other bug thread are the kind of errors that would arise from a buggy
gradient computation near the edge. However, some errors will remain even
after the bugfix, particularly at sharp corners.

An interesting extension to this method, one which preserves sharp corners,
was presented here a month ago, with an alleged improvement mentioned but
not presented because it's awaiting publication:
http://computergraphics.stackexchange.com/questions/306/sharp-corners-with-signed-distance-fields-fonts/2151#2151
<https://mail.liu.se/owa/redir.aspx?C=_Pf5WUc2KAk2vYEYxKCwed4eBYOtmjOwChdEp_8JqqWv4bIltV_TCA..&URL=http%3a%2f%2fcomputergraphics.stackexchange.com%2fquestions%2f306%2fsharp-corners-with-signed-distance-fields-fonts%2f2151%232151>

It's not clear from the presentation whether his conversion process is
automatic or requires manual editing of glyphs, but preserving sharp
corners would certainly improve distance field rendering of character
glyphs quite a lot.

**Comment by rougier** [comment]
Very impressive results. Do you know where it'll be published ? 
(Your second link doesn't work)

I've tried to examine the technique mentioned in the thread (https://lambdacube3d.wordpress.com/2014/11/12/playing-around-with-font-rendering/) but without much success.

**Comment by stegu** [comment]
Sorry about the mangled link. This first link is the only one I intended to
send. The "other" link was just some cut-and-paste cruft from the utterly
stupid webmail interface I am forced to use at work (courtesy of Microsoft).

http://computergraphics.stackexchange.com/questions/306/sharp-corners-with-signed-distance-fields-fonts/2151#2151

I don't know where it will be published. I wanted to ask, but it would
violate the guidelines for the "answer" threads at Stackexchange. Nobody
else seems to care much about that, but I guess I'm old fashioned. :)

**Comment by behdad** [comment]
> I wanted to ask, but it would violate the guidelines for the "answer" threads at Stackexchange.

Can't you comment on it?  I wanted to ask as well, but don't have enough points to be able to post a comment apparently!

**Comment by stegu** [comment]
My rep at Stackexchange is nonexistent, unfortunately, so a comment is out
of reach for me as well.

**Comment by rougier** [comment]
Sources have been released: https://github.com/Chlumsky/msdfgen

**Comment by stegu** [comment]
Great news! Thanks for the heads-up.
​
