### ISSUE TITLE
freetypegl ported successfully on android : but some "hacks"

### ISSUE THREAD

**Issue by shadd3** [rougier/freetype-gl#120]
Hello,
I have ported freetypegl on android, 
compilation ok + runtime ok
But as apparently is not officiial; I have used some hack to accomplish that:

+ I use vs2015 + CMake / VCMDDAndroid
https://github.com/Microsoft/CMake/tree/feature/VCMDDAndroid

+ cmake cmd line for VS2015 / Android

cmake -G "Visual Studio 14 ARM" %* .. -DCMAKE_SYSTEM_NAME=VCMDDAndroid ^
                                      -DAPPLE=1 ^
                                        -DOPENGL_INCLUDE_DIR=%NDK_ROOT%platforms\android-19\arch-arm\usr\include ^
                                        -Dfreetype-gl_BUILD_DEMOS=OFF ^
                                        -Dfreetype-gl_BUILD_MAKEFONT=OFF ^
                                        -Dfreetype-gl_BUILD_APIDOC=OFF ^
                                        -DFREETYPE_INCLUDE_DIRS=\thirdparty\freetype\include ^
                                        -DFREETYPE_LIBRARY=\thirdParty\freetype\buildAndroid_ARM\release\libfreetype.a ^
                                        -DOPENGL_gl_LIBRARY=%NDK_ROOT%platforms\android-19\arch-arm\usr\lib ^
                                        -DOPENGL_gl_INCLUDE=%NDK_ROOT%platforms\android-19\arch-arm\usr\include

As you are noticed; I use  APPLE=1  for android... and specified manualy the header file for opengl 

+ a modified version of opengl.h

```
#ifndef __OPEN_GL_H__
#define __OPEN_GL_H__

#if defined(__APPLE__)
#   include "TargetConditionals.h"
#   if TARGET_OS_SIMULATOR || TARGET_OS_IPHONE
#     if defined(FREETYPE_GL_ES_VERSION_3_0)
#       include <OpenGLES/ES3/gl.h>
#     else
#       include <OpenGLES/ES2/gl.h>
#     endif
#   else
#     include <OpenGL/gl.h>
#   endif
#elif defined(_WIN32) || defined(_WIN64)
	#include <GL/gl.h>
#else
	#include <GLES2/gl2.h>
#endif

#endif /* OPEN_GL_H */
```

do you have planned an official version for android ?
Best regards

**Comment by rougier** [comment]
That's really cool and I guess a lot of people will be interested.
I don't think we have any plan yet for Android, @adrianbroher do you confirm ?

**Comment by adrianbroher** [comment]
> I don't think we have any plan yet for Android, @adrianbroher do you confirm ?

No, there is no explicit support for it and I don't plan to add explicit support.  However, fixing the issue @shadd3 described should be no problem.

**Comment by rougier** [comment]
@shadd3 Could you make a PR from your proposed changes ?

**Comment by adrianbroher** [comment]
No, I will fix that properly.

**Comment by adrianbroher** [comment]
@shadd3 

he project should now be buildable without setting APPLE or modifying the OpenGL header.

**Comment by shadd3** [comment]
@adrianbroher : I will try asap; thank you
