### ISSUE TITLE
subpixel rendering mangled

### ISSUE THREAD

**Issue by blaayde** [rougier/freetype-gl#126]
I'm having an issue with the demos that use subpixel rendering.
here is a screenshot:
![ss0](https://cloud.githubusercontent.com/assets/6366859/18032255/309d1df6-6cce-11e6-99be-40ab3ed9034e.jpg)
this doesnt happen when the subpixel is turned off:
![ss1](https://cloud.githubusercontent.com/assets/6366859/18032257/3b8d3eee-6cce-11e6-9578-d4ea04d807a7.jpg)
Its across all demos that use subpixel:
![ss2](https://cloud.githubusercontent.com/assets/6366859/18032261/4cf7c9a6-6cce-11e6-8928-0a2b77179d97.jpg)
I have tried both using the freetype.lib that is in the freetype-gl repo and compiling several versions of freetype from source making sure that FT_CONFIG_OPTION_SUBPIXEL_RENDERING is defined in the ftoption.h file. always with the same result.

please advise

**Comment by rougier** [comment]
The rendering is really weird.
What is your configuration (system and GPU) ?

Could you try to use vshift=0 in https://github.com/rougier/freetype-gl/blob/master/shaders/text.frag
(this requires to rename the variable since it is a varying)

**Comment by blaayde** [comment]
I ruled out the shader.
since it happens even when i change the fragment shader to this;
void main()
{  
  gl_FragColor = vcolor;
  return;
 }
so the its happening outside the shader somewhere.

my system is:
core i7  / 9gig ram / win 7 64 
GPU: Nvidia GeForce GTX 960

**Comment by rougier** [comment]
Could you make the font bigger for the atb demo, I would like to see if the problem occurs only on the border of it the full glyph is wrong.

**Comment by blaayde** [comment]
for sure.
![no lcd](https://cloud.githubusercontent.com/assets/6366859/18040231/848fc566-6d79-11e6-8398-f78df8bd8fa8.jpg)
![lcd](https://cloud.githubusercontent.com/assets/6366859/18040232/861eb306-6d79-11e6-8432-76907d81f393.jpg)

I used the win magnifier to mag it 300% so you can clearly see the A glyph. 

Btw thank you for such quick responses, appreciate it.

**Comment by rougier** [comment]
It looks like only the first part of the texture is used with a shift in the y direction.
What I don't understand yet if why this happens given that the preparation of the buffer is the same with or without subpixel.

By the way, do you know if your monitor is a "regular" LCD one (I mean a pixel is an horizontal combination of RGB leds) ?

**Comment by rougier** [comment]
Looking at the source again, it might be a problem with the texture storage . It looks like the shader is trying to use a RGB texture as if it was a single channel texture. 


Could you try to use USE LCD_FILTERING_OFF in https://github.com/rougier/freetype-gl/blob/master/demos/subpixel.c#L71 and change GL_RGB  by GL_RED in https://github.com/rougier/freetype-gl/blob/master/demos/subpixel.c#L111 and check the result ?

**Comment by blaayde** [comment]
yeah, they are regular LCDs I tested it on 3 different monitors.

That worked !
heres the results:
![capture](https://cloud.githubusercontent.com/assets/6366859/18043598/e48d773e-6d96-11e6-96e9-1845997e792d.JPG)

Let me know if you'd like any help to correct the issue, I have a good amount of experience in graphics and shader coding.

**Comment by rougier** [comment]
Could you try LCD_FILTERING_ON but leave the GL_RED ? If for some reason freetype does not encode the glyph in RGB, the display should be ok.

**Comment by blaayde** [comment]
sure.

heres the result:
![result](https://cloud.githubusercontent.com/assets/6366859/18044277/14920982-6d9b-11e6-9291-95013bddc6a5.jpg)

**Comment by rougier** [comment]
And the other way around  (OFF + GL_RGB) ?

**Comment by blaayde** [comment]
That makes c++ bitchy :P:

![capt](https://cloud.githubusercontent.com/assets/6366859/18044896/f3f1a9c8-6d9d-11e6-8938-0f22a5c980d1.JPG)

**Comment by rougier** [comment]
Damn !

Looking again at the source,  https://github.com/rougier/freetype-gl/blob/master/texture-font.c#L489 is the place where we specify to use RGB for the encoding of the glyph but I don't know where to check if this was properly done. I suspect your freetype encoded the glyph using only one channel and this may be the reason for the mangling. But from what I remember, if freetype has not been compiled with LCD support, is should build a RGB glyph anyways (with R=G=B).

Can you check (e.g. using printf) the flag is actually set (FT_LCD_FILTER_LIGHT) and if yes, maybe use FT_LCD_FILTER_DEFAULT  or FT_LCD_FILTER_LEGACY ?

**Comment by blaayde** [comment]
Alright, here's my code changes. it confirms that the depth is 3 and the filters are being set correctly.

![code](https://cloud.githubusercontent.com/assets/6366859/18046534/5cea43f6-6da6-11e6-82d1-c1bb5c5a8fc7.jpg)

I tried all three filters to no avail:

![ss01](https://cloud.githubusercontent.com/assets/6366859/18046550/6ccbd3b6-6da6-11e6-8c6e-d6b7afd20110.jpg)
![ss02](https://cloud.githubusercontent.com/assets/6366859/18046553/6dfd8554-6da6-11e6-80e5-f006dcff5976.jpg)
![ss03](https://cloud.githubusercontent.com/assets/6366859/18046554/6ffa8bfe-6da6-11e6-8c6b-b7e2bb69c34b.jpg)

**Comment by rougier** [comment]
I'm starting to be out of ideas...

Just to be sure about what is actually stored in the texture, could print glyph information at 
https://github.com/rougier/freetype-gl/blob/master/texture-font.c#L600

We should have  `3*ft_bitmap.width = ft_bitmap.pitch` and `ft_bitmap.pixel_mode` should be  `FT_PIXEL_MODE_LCD` (see https://www.freetype.org/freetype2/docs/reference/ft2-basic_types.html#FT_Bitmap)

**Comment by blaayde** [comment]
Looks like your onto something. pitch is not 3* width:

![cre](https://cloud.githubusercontent.com/assets/6366859/18048416/f3837130-6daf-11e6-9b35-c1e6163529e9.JPG)

**Comment by rougier** [comment]
I need to check on my side but right now I cannot compile anymore...

**Comment by blaayde** [comment]
There's no rush.

**Comment by wmamrak** [comment]
I've got working code, I will PR in a second.

2016-08-29 12:15 GMT+02:00 blaayde <notifications@github.com>:

**Comment by rougier** [comment]
I managed to compile and get the same mangled ouput. Weird.
@wmamrak you found the bug ?

**Comment by wmamrak** [comment]
Yes, I was trying to update my old fork to the recent version, but I failed, so deleted it and forked again. PR ready.

**Comment by rougier** [comment]
@blaayde Does the new PR (merged) fix the bug on your machine ?

**Comment by wmamrak** [comment]
I have introduced a subtle bug, let me fix it.

**Comment by blaayde** [comment]
I just compiled and tested PR #128.  looks to be all working correctly. Thanks a lot for your help guys. much obliged. issue can be closed I think.
