### ISSUE TITLE
Non-english words sometimes display incorrectly.

### ISSUE THREAD

**Issue by silverness2** [rougier/freetype-gl#160]
Hi, I'm using the test program as described in Issue #158.  The text I am rendering is in Hindi, and the words are: "मेरा नाम शिल्पी है".

When I render the text, I get the following:
![hindi](https://cloud.githubusercontent.com/assets/25487118/24476482/99ebf682-1490-11e7-96e2-634085a35cdc.png)

The third word in the image does not match the third word in the text quoted above, although it is close.  The following code snippet is where I input the text in the modified markup demo code.  (The script is displayed correctly when I inspect the code using the Ubuntu 16.04 > TextEditor program, or if I embed the text in an html file and load it in a browser.)
```
    text_buffer_printf( buffer, &pen,
                        &big, "मेरा नाम शिल्पी है",
                        NULL );
```
Do you know why this might be occurring?  Are there any known issues with left-to-right languages whose non-Latin characters are connected to form words?

**Comment by rougier** [comment]
Yes, I think non-latin characters may be problematic. You have to look at the harfbuzz demo (https://github.com/rougier/freetype-gl/tree/master/harfbuzz) that may give a better results because the harfbuzz library is able to handle any language.
