### ISSUE TITLE
load font from memory fails

### ISSUE THREAD

**Issue by skanti** [rougier/freetype-gl#163]
I load a `ttf` as binary as

``` c++
static void load_all_bytes_from_file(std::string filename, std::vector<char> &buffer, int &buffer_size) {
    std::ifstream ifs(filename, std::ios::binary| std::ios::ate);
    std::ifstream::pos_type pos = ifs.tellg();

    buffer.resize(pos);
    buffer_size = (int)pos;

    ifs.seekg(0, std::ios::beg);
    ifs.read(&buffer[0], pos);
}
```

Then I provide that buffer to 

``` c++
texture_font_new_from_memory(atlas, 28, buffer.data(), buffer.size());
```

but it will break down at 

``` c++
FT_Load_Glyph
```

---

Any thoughts? I assume I am supposed to load it differently?

**Comment by rougier** [comment]
Did you solve it in the end ?

**Comment by skanti** [comment]
Yes, the problem was that the `buffer` has to remain alive throughout the run-time. I deallocated it after the first use which caused problems at loadings. Maybe you should include it somewhere in your documentation:)

**Comment by rougier** [comment]
PR welcome !
