### ISSUE TITLE
How do I specify Debug Build on Mac using CMake Gui?

### ISSUE THREAD

**Issue by rogermc2** [rougier/freetype-gl#171]

**Comment by rougier** [comment]
You mean there is no option using ccmake ?

**Comment by rogermc2** [comment]
No, I can build freetype-GL using CMake.
What I want to do is to make a build with debug capability (-g).

**Comment by rogermc2** [comment]
Now that I know what to look for, Googling seems to have bought up plenty on the subject so that should provide needed help.
Thanks for your prompt reply.
