### ISSUE TITLE
Single font encompassing multiple atlases 

### ISSUE THREAD

**Issue by monolifed** [rougier/freetype-gl#180]
Is a font encompassing multiple atlases possible? As far as I can tell the library assumes the font will fit in a single atlas.
Also, the font-manager uses a single atlas for every font. It could be better if it created a new atlas if the previous one is full (i.e. when the new font won't fit in it, but then there is also the problem of a font not fitting in an atlas of the given dimensions).

**Comment by rougier** [comment]
Best would be to have several atlases and to bind them if necessary. However, I have no time right now to do that. Can you give a try?

**Comment by monolifed** [comment]
Thanks, that should work too. But I changed atlas in texture font to a vector of atlases and font-manager to create atlases when load_glyphs (and changed its return to char* because number of characters was not very useful to continue from where it left) fails.
