### ISSUE TITLE
Is there a way to load glyph data into texture with a padding/margin in the glyph's texture?

### ISSUE THREAD

**Issue by DarkShinz** [rougier/freetype-gl#181]
Hey guys,

Been trying to add a glow effect though the way my code is loading stuff I have no idea at how to generate the font texture with a larger draw area, so one option is to add a margin or padding into the glyph's texture, though I haven't seen a way to do it. Even though at the demo distance-field-2 it adjust the destination vertices with a vec4 variable called bbox glow still will be cutted in this demo. 
Any tips?

**Comment by rougier** [comment]
There is a padding option actually: https://github.com/rougier/freetype-gl/blob/master/texture-font.c#L569

**Comment by DarkShinz** [comment]
@rougier oh, thank you : >
