### ISSUE TITLE
Cannot create a project. Cmake issue

### ISSUE THREAD

**Issue by DonTweaks** [rougier/freetype-gl#184]
Hello
I am working on windows
I want to build ftgl,  but I am getting wried error. I been looking for solution, found some case in `Issues`, but those settings guy showed does not work for me. Still same error.

I am doing cmake like this:

open cmd,
cd C:/.../BuildFTGL
in BuildFTGL I move cmake.exe into the console and then move C:/.../freetype-gl-master there.
I am getting following error:
![obraz](https://user-images.githubusercontent.com/29126744/40590329-30383ba4-61fd-11e8-8e7a-6779bcefbaf1.png)

I did watch CMakeError.log and CMakeOutput.log, but those files could not help me.
[CMakeError.log](https://github.com/rougier/freetype-gl/files/2042978/CMakeError.log)
[CMakeOutput.log](https://github.com/rougier/freetype-gl/files/2042979/CMakeOutput.log)

Also I tried gui. Same resault:

First:
![obraz](https://user-images.githubusercontent.com/29126744/40590350-8150620a-61fd-11e8-9026-022da2b43230.png)

Then:
![obraz](https://user-images.githubusercontent.com/29126744/40590360-9e28d7f4-61fd-11e8-90ad-81a8f6e4c55c.png)

Next I unmarked demos as https://github.com/rougier/freetype-gl/issues/82 said and generate once again:

![obraz](https://user-images.githubusercontent.com/29126744/40590394-3e9c4b80-61fe-11e8-9bfc-976cad63bb87.png)

How to generate a project properly?

**Comment by adrianbroher** [comment]
As you can see CMake searches for an installation of [Doxygen], a tool to generate HTML documentation from C source code.  So either install Doxygen to fix the project generation or disable the document generation by calling cmake with the parameter `-Dfreetype-gl_BUILD_APIDOC=OFF` like 

```
cmake -Dfreetype-gl_BUILD_APIDOC=OFF <path to freetype-gl source>
```

or do the same by unchecking the variable of the same name in the GUI.

[Doxygen]: http://www.stack.nl/~dimitri/doxygen/

**Comment by DonTweaks** [comment]
Thanks! That works! Now cmake cannot find glfw3. How to disable it?

**Comment by DonTweaks** [comment]
Thank you so much <3
