### ISSUE TITLE
Text not rendering

### ISSUE THREAD

**Issue by adam0310** [rougier/freetype-gl#185]
Hi! I am trying to render text with freetype gl. If I understand correctly function `texture_font_get_glyph` should render char that I give it, but I can only see a big black square:
![is now](https://user-images.githubusercontent.com/35536269/40791060-d5f618da-64f6-11e8-8c70-cdee8a619134.PNG)
In the tutorial I found on youtube in this black square renders red characters.[https://www.youtube.com/watch?v=Rsdc6I80aFQ&list=PLlrATfBNZ98fqE45g3jZA_hLGUrD4bo6_&index=24](https://www.youtube.com/watch?v=Rsdc6I80aFQ&list=PLlrATfBNZ98fqE45g3jZA_hLGUrD4bo6_&index=24)
I have glfw 3.2.1 and freetype 2.9.1. I use older version of freetype-gl. This presented in the tutorial (I have tried with this latest, but it didnt help). Please help!

**Comment by rougier** [comment]
Is there any error message in the console ?

**Comment by adam0310** [comment]
no

**Comment by rougier** [comment]
Did you manage to run the demos bundled with freetype-gl?

**Comment by rougier** [comment]
What are the messages?

**Comment by adam0310** [comment]
there are 151 errors. You can see some here (they are in Polish, but you can see their codes)
![error](https://user-images.githubusercontent.com/35536269/41188607-5d52e9aa-6bc0-11e8-9ead-5a508f1638b8.PNG)
Most of them are in files harfbuzz-texture.c and harfbuzz.c

**Comment by rougier** [comment]
Most probably the harfbuzz library is missing on your system.

**Comment by adam0310** [comment]
Do I need this library to get freetype work?

**Comment by rougier** [comment]
No, but then you have to disable the building of the harfbuzz demo.

**Comment by adam0310** [comment]
I disabled these files and now i have 2 errors:
Cannot include files vera-16.h and fontconfig/fontconfig.h. I cant find these files. When i comment this includes i have new errors

**Comment by DonTweaks** [comment]
W jaki sposób wgrałeś glfw do freetype, bo kurczę nie wiem jak to zrobić ;/

**Comment by adam0310** [comment]
DonTweaks Nie trzeba wgrywać glfw do freetype. glfw robi tylko okno. Wyświetlanie w tym oknie to już sam opengl. freetype-gl powinien sam wyswietlić ten tekst

**Comment by DonTweaks** [comment]
Tak, tylko, że jak pobieram ftgl to nie mam glfw wgranego w folder więc muszę go pobrać, zbudować i wtedy jakoś wrzucić to freetype.

**Comment by adam0310** [comment]
DonTweaks wpisz w google glfw znajdz tam oficjalną stronę i pobierz biblioteki. Jak zainstalować biblioteki masz mnóstwo poradników na youtube.

**Comment by adam0310** [comment]
Rougier What must i do to build this demo? Is there more files i must disable?

**Comment by rougier** [comment]
you have to configure cmake before building and look at the different options. Also,  fontconfig is missing (header files probably)

**Comment by adam0310** [comment]
How can i configure cmake?

**Comment by rougier** [comment]
Have a look at cmake documentation, it is explained.

**Comment by adam0310** [comment]
When I try to run CMakeLists.txt it throws an error Could not find Doxygen and when I try to run demos\CMakeLists.txt it throws error Could not find package configuration file privided by "glfw3"

**Comment by adam0310** [comment]
Sorry i was a missclick

**Comment by adam0310** [comment]
Jaszczolt i have glfw3 but does it matter which version it is?

**Comment by DonTweaks** [comment]
I do not know.

**Comment by DonTweaks** [comment]
Have the same problem. Maybe @rougier  knows what to do with it or knows a person who'd help.

**Comment by wmamrak** [comment]
After installing GLFW (using CMake), in
${CMAKE_INSTALL_PREFIX)/lib/cmak/glfw3 there are config files needed
(glfw3Config.cmake and others). When configuring freetype-gl in CMake add
entry glfw3_DIR and set it to ${CMAKE_INSTALL_PREFIX)/lib/cmak/glfw3
(replace ${CMAKE_INSTALL_PREFIX} with real directory). If this won't help,
specify GLFW3_INCLUDE_DIR, GLFW3_LIBRARY_DIR and GLFW3_LIBRARY.

czw., 14 cze 2018 o 21:31 DonTweaks <notifications@github.com> napisał(a):

**Comment by adam0310** [comment]
Must I instal GLFW using cmake? Can't i just have lib file?

**Comment by wmamrak** [comment]
Specify GLFW3_INCLUDE_DIR, GLFW3_LIBRARY_DIR, GLFW3_LIBRARY and check, I
don't know.

sob., 16 cze 2018 o 19:11 Adam <notifications@github.com> napisał(a):

**Comment by adam0310** [comment]
zI don't know if I do it correctly, because I am new to cmake. I tried to write this code to demos/CMakeLists.txt and CMakeLists.txt and it didn't work. I tried with this:
`set(GLFW3_INCLUDE_DIR "../GLFW")
set(GLFW3_LIBRARY_DIR "..")
set(GLFW3_LIBRARY "glfw3.lib")`
and this:
`set(GLFW3_INCLUDE_DIR "GLFW")
set(GLFW3_LIBRARY_DIR "")
set(GLFW3_LIBRARY "glfw3.lib")`
Am I doing this wrong, or must i install glfw with cmake?(my glfw3.lib file is in thesame folder as CMakeLists.txt, GLFW folder too)

**Comment by DonTweaks** [comment]
1. Pobierasz glfw ze stronki
2. Rozpakowywujesz i tworzysz gdzieś sobie folder o nazwie np. buildglfw
3. Odpalasz cmd i wpisujesz cd buildglfwi wciskasz enter
4. Wchodzisz w folder z cmake i aplikację cmake.exe i trzymając lewym przyciskiem myszy na nią przeciągasz na cmd
5. Przeciągasz w analogiczny sposób folder z glfw (ten rozpakowany) i klikasz enter.
6. Gdy już ci się załaduje wchodzisz w folder buildglfw, otwierasz projekt ALL_BUILD i buildujesz
7. Wchodzisz w folder buildglfw/CMakeFiles/Export/lib/cmake/glfw3 i kopiujesz `glfw3Targets.cmake`
8. Cofasz się do buildglfw i wchodzisz w src - tam wklejasz `glfw3Targets.cmake`
9. Pobierasz ftgl
10. Wchodzisz w cmake-gui
11. Ustawiasz source code na ftgl-master (ten folder który pobrałeś z githuba)
12. Tworzysz folder buildftgl i wybierasz go jako ten w którym mają być buildowane rzeczy
13. Dodajesz entry: 
a)GLFW3_INCLUDE_DIR jako path: folderZglfw/include
b)GLFW3_LIBRARY_DIR jako path:buildglfw/src/Debug
c)GLFW3_LIBRARY jako filepath: buildglfw/src/Debug/glfw3.lib
14. Klikasz Generate i generujesz projekt
15. Pojawia ci się błąd, bo masz włączonego Doxygen
16. Odklikujesz freetype-gl_BUILD_APIDOC
17. Usuwasz wszystkie pliki, które znajdują się w folderze buildftgl
18. Buildujesz od nowa i cieszysz się działającymi demosami

**Comment by rougier** [comment]
What do you mean correct my mistakes? And I'm not sure how to highlight the comment. Maybe you can open a new issue with just the installation procedure for windows.

**Comment by DonTweaks** [comment]
>Language mistakes, I believe
True

**Comment by adam0310** [comment]
OK, I found the solution for this problem. Now everything perfectly works. Thanks for help.

**Comment by MyForce2** [comment]
I'm having the same problem, can you please share your solution?

**Comment by rougier** [comment]
I think the solution is a few posts above.

**Comment by LordVeggie** [comment]
sorry for bothering i also have a similar problem with the same episode .
i get text to draw the blocks the right shape but they are all just black no letters of any color at all .
![image](https://user-images.githubusercontent.com/35328638/45056968-a5510980-b094-11e8-9bd9-75e0c4ce5ee8.png)

**Comment by LordVeggie** [comment]
can any one ask adam0310 what he did because the solution does nothing to the problem i still get the black blocks. pls and tanx

**Comment by rougier** [comment]
Did you manage to run one of the demo? Is the output correct? If not, maybe it's better to open a new issue with a screenshot of your outputs on the demo.

**Comment by LordVeggie** [comment]
found the solution down load the code of cherno (freetype gl only and past it over the freetype code you down loaded from freerype gl website ) . then go to line 303  in texture-atlas.c and make the( #if 0 TO A  #if 1)
then you should have the text rendering
