### ISSUE TITLE
Why cannot I pass texture data directly to my texture class?

### ISSUE THREAD

**Issue by DonTweaks** [rougier/freetype-gl#186]
Hi! I want to use my own 2d texture class to create a font texture. 
I have class called GLTexture2D which pass w, h and data to the open gl calls

```
GLTexture2D::GLTexture2D(Uint width, Uint height, void* data)
{
	w = width;
	h = height;

	texture = LoadFromFile(data); //texture is GLuint type
}

Uint GLTexture2D::LoadFromFile(void* data)
{
        Uint tex;
	glCall(glGenTextures(1, &tex));
	glCall(glBindTexture(GL_TEXTURE_2D, tex));

	glCall(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT));
	glCall(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT));
	glCall(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST));
	glCall(glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST));

	glCall(glTexImage2D(GL_TEXTURE_2D, 0, GL_LUMINANCE_ALPHA, w, h, 0, GL_LUMINANCE_ALPHA, GL_UNSIGNED_BYTE, data));
	glCall(glGenerateMipmap(GL_TEXTURE_2D));
	glCall(glBindTexture(GL_TEXTURE_2D, 0));

	return tex;
}
```

and text class which creates ftgl atlas and font, and should pass data to my class
```
Font::Font(const std::string& filePath, int size)
{
	ftAtlas = ftgl::texture_atlas_new(512, 512, 1);
	ftFont = ftgl::texture_font_new_from_file(ftAtlas, size, filePath.c_str());

	texture2D = new GLTexture2D(512, 512, ftAtlas->data);
}
```

and in main I do 

`Font* font = new Font("Files/Fonts/arial.ttf", 50);`

and I am getting gl error pointing at glTexImage2D with `GL_INVALID_VALUE `, but none of those errors should happenes I think.

How to fix it?
Why do I get error like this?

**Comment by DonTweaks** [comment]
How to build demos? I have got problems with glfw. This is how I set it on

![image](https://user-images.githubusercontent.com/29126744/41527379-44b8378c-72e7-11e8-9412-0652de02abc2.png)

I do not know what directory should I set in glfw3_DIR. What kind of files should it contain?

**Comment by wmamrak** [comment]
Compile and install (using CMake) GLFW. Set glfw3_DIR to
${CMAKE_INSTALL_PREFIX)/lib/cmake/glfw3 (replace ${CMAKE_INSTALL_PREFIX}
with real directory).

pon., 18 cze 2018 o 11:06 DonTweaks <notifications@github.com> napisał(a):

**Comment by DonTweaks** [comment]
I did it and there is no lib directory. 

cmd -> cd .../Build/32 -> cmake glfw folder 

I have only those folders:
![obraz](https://user-images.githubusercontent.com/29126744/41534569-4d8ed9a2-72ff-11e8-84da-697392f9d352.png)

**Comment by wmamrak** [comment]
I didn't say anything about the lib directory.
Generated files are in src/Debug and src/Relase folders, at least fo me.
But you need to install glfw (i.e. build the INSTALL project from inside
VS) and use the generated config files when configuring freetype-gl.

pon., 18 cze 2018 o 13:56 DonTweaks <notifications@github.com> napisał(a):

**Comment by DonTweaks** [comment]
>I didn't say anything about the lib directory.

You did

>Compile and install (using CMake) GLFW. Set glfw3_DIR to ${CMAKE_INSTALL_PREFIX)`/lib`/cmake/glfw3 (replace ${CMAKE_INSTALL_PREFIX} with real directory).

;

>Generated files are in src/Debug and src/Relase folders, at least fo me. But you need to install glfw (i.e. build the INSTALL project from inside VS) and use the generated config files when configuring freetype-gl.

I built it inside VS and I have got src/Debug and src/Release but only with .lib. .cmake files are inside src and when I set glfw3_DIR to be `src` directory (where are 
![obraz](https://user-images.githubusercontent.com/29126744/41550457-1c56ecc4-7329-11e8-8f9b-5da6d9878f4a.png) ) I am getting this error.


```
CMake Error at C:/Users/Don/Desktop/glfw-3.2.1/Build/32/src/glfw3Config.cmake:1 (include):
  include could not find load file:

    C:/Users/Don/Desktop/glfw-3.2.1/Build/32/src/glfw3Targets.cmake
Call Stack (most recent call first):
  demos/CMakeLists.txt:40 (find_package)
```

**Comment by DonTweaks** [comment]
I have reinstalled all files (cmake, ftgl, glfw) and built them again and it works. Thank you!
