### ISSUE TITLE
makefont building error (linking with GL)

### ISSUE THREAD

**Issue by fillest** [rougier/freetype-gl#2]
``` bash
Scanning dependencies of target demo-texture
[ 96%] Building C object CMakeFiles/demo-texture.dir/demo-texture.c.o
Linking C executable demo-texture
[ 96%] Built target demo-texture
Scanning dependencies of target makefont
[100%] Building C object CMakeFiles/makefont.dir/makefont.c.o
Linking C executable makefont
/usr/bin/ld: libfreetype-gl.a(texture-atlas.c.o): undefined reference to symbol 'glTexImage2D'
/usr/bin/ld: note: 'glTexImage2D' is defined in DSO /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/libGL.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/libGL.so: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make[2]: *** [makefont] Error 1
make[1]: *** [CMakeFiles/makefont.dir/all] Error 2
make: *** [all] Error 2
```

Ubuntu 12.04 x86_64. Source tree from master.
Other demos work fine.
Some people reported this issue too (http://code.google.com/p/freetype-gl/issues/detail?id=59).

On my system it seems like it links with wrong DSO (mesa instead of nvidia):

``` bash
ls -lah /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/libGL.so
lrwxrwxrwx 1 root root 13 Jun 19 00:54 /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu/libGL.so -> mesa/libGL.so
```

Just a speculation: this bug (check https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/943162) happens with some other software. With compile-time dynamic linking the mentioned bug doesn't occur (on my system) - but maybe with static library ("/usr/bin/ld: libfreetype-gl.a(texture-atlas.c.o)") this bug occures too..
By the way, "export LD_LIBRARY_PATH=/usr/lib/nvidia-304-updates" usually makes dlopen (runtime library loading) work, but building freetype-gl still fails (I tried rebuilding from scratch after changing LD_LIBRARY_PATH) - this is strange.

**Comment by adrianbroher** [comment]
> I also needed to add SET( ANT_TWEAK_BAR_INCLUDE_PATH "") to let CMake run on my system (I don't have AntTweakBar installed). Am I right to assume that this shouldn't change anything for anybody else since FIND_PACKAGE( AntTweakBar ) resets the variable?

This breaks the build for me. CMake is unable to find AntTweakBar even it is installed. Removing said line fixes that just fine. I will take a look at how to fix this properly sometime.

    $ cmake ../freetype-gl.git/
    -- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
    -- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
    -- Looking for gethostbyname
    -- Looking for gethostbyname - found
    -- Looking for connect
    -- Looking for connect - found
    -- Looking for remove
    -- Looking for remove - found
    -- Looking for shmat
    -- Looking for shmat - found
    -- Looking for IceConnectionNumber in ICE
    -- Looking for IceConnectionNumber in ICE - found
    -- Found X11: /usr/lib64/libX11.so
    -- Found OpenGL: /usr/lib64/libGL.so  
    -- Found GLUT: /usr/lib64/libglut.so  
    -- Found Freetype: /usr/lib64/libfreetype.so (found version "2.5.0") 
    -- Found GLEW: /usr/lib64/libGLEW.so  
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
    -- Found Fontconfig: /usr/lib64/libfontconfig.so  
    -- Could NOT find AntTweakBar (missing:  ANT_TWEAK_BAR_INCLUDE_PATH) 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/adrian/Projekte/freetype-gl/freetype-gl.gcc

**Comment by rougier** [comment]
I guess it makes sense that cmake complains about missing anttweakbar since the path is set to "". Maybe it is a bad solution and the first problem should be solved differently.
