### ISSUE TITLE
Detect Retina display

### ISSUE THREAD

**Issue by thewoz** [rougier/freetype-gl#228]
Hi,
there is a way to detect if a program is running on a Retina display?
thanks

**Comment by rougier** [comment]
Sorry for late answer. Did you find an answer ? If you use GLFW, I think you can detect it.

**Comment by thewoz** [comment]
Hi, wrote here for mistake. 
Yes I use GLFW I have posted the same question there. until now no answer yet

**Comment by rougier** [comment]
You can have a loo, at GLFW documentation and search fro framebuffer_size vs window_size.
