### ISSUE TITLE
Build with tests enabled break: Error evaluating generator expression: $<TARGET_FILE:ansi>

### ISSUE THREAD

**Issue by yurivict** [rougier/freetype-gl#234]
```
  Error evaluating generator expression:

    $<TARGET_FILE:ansi>

  No target "ansi"
Call Stack (most recent call first):
  tests/CMakeLists.txt:32 (cmp_test)
```

**Comment by rougier** [comment]
Thanks for the report. Can you give some context (OS and any cmake options you may have)?

**Comment by yurivict** [comment]
OS: FreeBSD 12.2
cmake-3.19.4
cmake options: ```-Dfreetype-gl_BUILD_DEMOS:BOOL=true -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -L/usr/local/lib -lGLEW -lfreetype -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -L/usr/local/lib -lGLEW -lfreetype -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -L/usr/local/lib -lGLEW -lfreetype -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -Dfreetype-gl_BUILD_APIDOC:BOOL=OFF -Dfreetype-gl_BUILD_TESTS:BOOL=OFF```

**Comment by rougier** [comment]
Thanks. I'm not sure what's happening. If you disable tests, does it build?

**Comment by yurivict** [comment]
Yes.

**Comment by rougier** [comment]
And if you specifically disable ansi target from test, I imagine it also builds, right?

**Comment by yurivict** [comment]
I can't reproduce this any more. Perhaps the cmake version changed.
