### ISSUE TITLE
Error reporting behaviour too invasive

### ISSUE THREAD

**Issue by namaenonaimumei** [rougier/freetype-gl#241]
In current state all error reporting is being done by streaming freetype output directly to stderr buffer, without any means to change it on end-user's side.
This may be unwanted behaviour, as in multi-threaded environment, this could lead to output buffer corruption.

This could be fixed by providing end-user with means to change error handling behaviour.

**Comment by rougier** [comment]
Thanks for the report and the patch. It has been merged.
