### ISSUE TITLE
freetype-gl-err files missing?

### ISSUE THREAD

**Issue by mikeiannacone** [rougier/freetype-gl#256]
I noticed that the `harfbuzz` dir contains `freetype-gl-err.c` and .h files, which link to files in the parent directory, which are not present.

This is generating cmake errors, as seen in this travis output, and the same error in my local environment. 
https://travis-ci.com/github/mikeiannacone/freetype-gl/builds/231280334#L1177

Is there a fix that I'm overlooking? Or does someone have these available?

**Comment by mikeiannacone** [comment]
found/added these files in the commit below - is this correct? If so should I send a PR?

https://github.com/mikeiannacone/freetype-gl/commit/4ba2ba7cc334237359b05b8ffbda5ca995324c25

**Comment by rougier** [comment]
Sorry for the delay. Did you find a fix ? (I did not have tome to look)

**Comment by mikeiannacone** [comment]
No, I never did figure it out. I tabled this to work on a different problem, but I'm planning to pick it back up now, so let me know if you have any thoughts on this.

**Comment by mikeiannacone** [comment]
I'm not sure what the problem was (is?) but I just ended up using a (much) older version, which avoided the issue.

In case you (or anyone that stumbles across this) is curious:
I was building [this project](https://github.com/mikeiannacone/simreprap) and I pulled a somewhat newer (but still outdated) version of freetype-gl [from this branch, upstream](https://github.com/buserror/simreprap/tree/dev-mega2560/shared/libfreetype-gl) which looks like it did not include harfbuzz.

**Comment by vadim10012** [comment]
These files are here [https://github.com/rougier/freetype-gl/tree/d75d470100470bcc5b4ca1b762458141df453909](url)
