### ISSUE TITLE
Versioning and mesonbuild's wrapdb

### ISSUE THREAD

**Issue by tmayoff** [rougier/freetype-gl#266]
I'd like to be able to use this project via [mesonbuild's wrapd](https://mesonbuild.com/Wrap-dependency-system-manual.html) dependency system, the biggest hurdle to it is the fact that this library doesn't have a versioning scheme which they rely on in the wrapdb. Would it be possible to create releases or tag versions?

Also I was planning on providing the meson build definitions directly in the wrapdb entry, however I can also make a PR to have them in this repo as well

**Comment by rougier** [comment]
A versioning scheme would be most welcome actually. As for the meson build definition, I do not use it but I do not see a problem including what is necessary. If you can make (two sepatate) PRs, that would be great!

**Comment by tmayoff** [comment]
I'll make the PR with the mesonbuild stuff a bit later this week, but as for the versioning are there changes to the code that need to be made or could you follow something like this. https://semver.org/. And make releases via [Github ](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases )
