### ISSUE TITLE
undefine symbol:FT_PIXEL_MODE_BGRA  in texture-font.c

### ISSUE THREAD

**Issue by PanuiQ** [rougier/freetype-gl#270]
undefine symbol:FT_PIXEL_MODE_BGRA  in texture-font.c

FT_PIXEL_MODE_BGRA   define in ftimage.h  Since 2.5 version

in windows directory ,freetype 's version is 2.4.7

**Comment by rougier** [comment]
It seems to be defined [here](https://freetype.org/freetype2/docs/reference/ft2-basic_types.html#ft_pixel_mode)

**Comment by PanuiQ** [comment]
> It seems to be defined [here](https://freetype.org/freetype2/docs/reference/ft2-basic_types.html#ft_pixel_mode)

Thanks, I've fixed this issue

**Comment by yeokaiwei** [comment]
Hi Rougier,

Encountered the same issue with texture-font.c.

ftimage.h does not contain the definition for FT_PIXEL_MODE_BGRA (attached screenshot).

However, if we add FT_PIXEL_MODE_BGRA to the enum, FT_PIXEL_MODE_MAX will increase by 1.


Thank you.

```
    if( ft_bitmap.pixel_mode == FT_PIXEL_MODE_BGRA && self->atlas->depth == 4 )
    {
        // BGRA in, RGBA out
        for( i = 0; i < src_h; i++ ) {
            int j;
            for( j = 0; j < ft_bitmap.width; j++ ) {
                uint32_t bgra, rgba;
                bgra = ((uint32_t*)src_ptr)[j];
#if __BYTE_ORDER == __BIG_ENDIAN
                rgba = rol(__builtin_bswap32(bgra), 8);
#else
                rgba = rol(__builtin_bswap32(bgra), 24);
#endif
                ((uint32_t*)dst_ptr)[j] = rgba;
            }
            dst_ptr += tgt_w * self->atlas->depth;
            src_ptr += ft_bitmap.pitch;
        }
    }
```


**![Screenshot 2024-07-18 203613](https://github.com/user-attachments/assets/de0e6870-7939-438b-8bb3-49656733e67c)**

**Comment by yeokaiwei** [comment]
@PanuiQ  May I ask how you solved this issue?

**Comment by rougier** [comment]
Sorry  being late to answer. Not sure to fully understand your bug description. Can you elaborate a bit?
