### ISSUE TITLE
Signed distance field optimizations

### ISSUE THREAD

**Issue by duvisit** [rougier/freetype-gl#275]
After trying demos and reading through source code of `edt3aafunc.c` I think there is some room for small optimizations.

- Use float instead of double in distance field computations.

- Remove lines from `computegradient()` function 

---
    #if 0
    glength = gx[k]*gx[k] + gy[k]*gy[k];
    if(glength > 0.0) { // Avoid division by zero
        glength = sqrt(glength);
        gx[k]=gx[k]/glength;
        gy[k]=gy[k]/glength;
    }
    #endif
---

and lines from `edgedf()` function

---
    #if 0
        if(glength>0) {
            gx = gx/glength;
            gy = gy/glength;
        }
        /* Everything is symmetric wrt sign and transposition,
         * so move to first octant (gx>=0, gy>=0, gx>=gy) to
         * avoid handling all possible edge directions.
         */
        gx = fabs(gx);
        gy = fabs(gy);
    #else
        gx = fabs(gx/glength);
        gy = fabs(gy/glength);
    #endif
---

Division by zero is handled by the `if (gx==0 || gy==0)` few lines before.

- In `edtaa3()` function use:
---
      #if 0
        if(a > 1.0) a = 1.0;
        if(a < 0.0) a = 0.0; // Clip grayscale values outside the range [0,1]
        if(a == 0.0) return 1000000.0; // Not an object pixel, return "very far" ("don't know yet")
      #else
        if(a <= 0.0f) return 1000000.0f;
        if(a > 1.0f) a = 1.0f;
      #endif
 ---

Hope this doesn't break anything.

Great library, bye.

**Comment by rougier** [comment]
Maybe not worth the change.

**Comment by duvisit** [comment]
I agree. PR #278 is better.
