### ISSUE TITLE
Conflict with GLM

### ISSUE THREAD

**Issue by Trouvist** [rougier/freetype-gl#40]
GLM uses identically named types for the matrix and vector types created by freetype-gl.  All of the glm types are protected by namespaces, but not so in freetype-gl, so it can cause issues for files which have previous "using glm::vec4" etc declarations.  

What's the possibility of renaming those data types to something which will have fewer name conflicts, since names like mat4, vec4, etc are common enough to cause headaches for more than just myself?

**Comment by LinusU** [comment]
I think that this issue should be closed now that #48 have been merged.

**Comment by rougier** [comment]
Thanks for having noticed.
