### ISSUE TITLE
Example demo-font not working: error in vertex_buffer_new.

### ISSUE THREAD

**Issue by Ploppz** [rougier/freetype-gl#55]
Hi. Trying to run [this](http://freetype-gl.googlecode.com/svn/wiki/doc/demo-font_8c-example.html) example. I had to alter a few things to make it run (but not any logic). However, when it runs, I get this error:
```
program: /home/ploppz/work/c++/lib/freetype-gl/vector.c:46: vector_new: Assertion `item_size' failed.
```
After looking at all function calls to `vector_new` that appears in the `freetype-gl` library, it appears that the error has to be in line `199` of `vertex-buffer.c`, where `stride` must be equal to 0.

In the program, this is how `vertex_buffer_new` is called: `buffer = vertex_buffer_new( "v3f:t2f:c4f" );`

How can I change the format sent to `vertex_buffer_new` so that it evaluates a `stride` that's != 0?

I'm also wondering if the examples are outdated.

Edit: Also, where can I find documentation of the format string used in `vertex_buffer_new`?

Thanks.

**Comment by rougier** [comment]
Did you get sources from https://github.com/rougier/freetype-gl (the example you sent is on googlecode) ? (I dont' find the line you're referring to in `vertex_buffer.c`)

For the forme, you might want to look at: https://github.com/rougier/freetype-gl/blob/master/vertex-attribute (or build the doc in the doc directory).

**Comment by Ploppz** [comment]
Sorry, 199 is a typo and it meant to sat `119`!

**Comment by Ploppz** [comment]
Ah, I used the code from github, and it works now! I don't know what made me take code from google rather than github.. Thanks.
