### ISSUE TITLE
Instructions for using this project

### ISSUE THREAD

**Issue by TheKnarf** [rougier/freetype-gl#67]
I'm having a bit of trouble trying to figure out how to use this library in my own project, the examples are okay, but it would be nice with some build instructions. Exs: does this build and install the library on my computer? Is there a CMakeModule for this library I can include in my own project? Can I build this without building the demoes? Do I need AntTweekBar to build this when I'm not using it in my own project? Can I add this project as a submodule on git and reference the CMakeList in some way? Would it be best to copy paste the source code and write my own buildfile? And how would this work if I'm trying to create a reproducible build working across several platform?

The demoes is okay for showing how to use the product, but I'm having a few problems trying to figure out how to use this with my own project. So it would be nice with some instructions in the Readme-file on how to build and best reference the library.

**Comment by StrikerMan780** [comment]
Agreed, this information would be nice.

**Comment by rougier** [comment]
Freetype-gl is not a library because the philosophy is to take the part you want and re-use your own objects where you want. For example, when included in a projects, chances are that you have already a data structure for vertex buffer, vec2, vec4, matrices, etc.
