### ISSUE TITLE
How is freetype-gl designed to display text? I'm working on writing a C# version of freetype.

### ISSUE THREAD

**Issue by bitzhuwei** [rougier/freetype-gl#73]
freetype-gl works really great! And I want to write a C# version of freetype. So counld anyone help to tell how freetype-gl is designed to display text? Do I need any OS API or other staff rather than C language?

**Comment by rougier** [comment]
Freetype-gl use textured font, both regular and signed distance one. You can find more information at:

http://jcgt.org/published/0002/01/04/ and http://jcgt.org/published/0002/01/04/paper.pdf

Porting to C# should not

**Comment by bitzhuwei** [comment]
Thank you!
