### ISSUE TITLE
Issue with building on Mac OS X

### ISSUE THREAD

**Issue by AngeloG** [rougier/freetype-gl#76]
Building on OS X is giving me the same problems shown in [this bugreport of another project](https://github.com/ofnode/of/issues/15).

The (admittedly hacky) solution is to simply add `"/usr/local/include/freetype2/"` before `${FREETYPE_INCLUDE_DIRS}` in `include_directories`. This makes it build fine.

The use of an absolute path is justified by the notion that folder paths on Windows and OS X barely (or never) change.

Is this worth merging in master branch?

**Comment by rougier** [comment]
Can you describe the error you get  exactly (the issue is pretty long and in the end I'm not sure of the exact problem)

**Comment by AngeloG** [comment]
```
Scanning dependencies of target freetype-gl
[  3%] Building C object CMakeFiles/freetype-gl.dir/mat4.c.o
[  6%] Building C object CMakeFiles/freetype-gl.dir/texture-atlas.c.o
[  9%] Building C object CMakeFiles/freetype-gl.dir/texture-font.c.o
In file included from /Users/angel/dev/TomatoLib/TomatoLib/TomatoLib/Libaries/freetype-gl/texture-font.c:34:
/Library/Frameworks/Mono.framework/Headers/ft2build.h:56:10: fatal error: 'freetype/config/ftheader.h' file not found
#include <freetype/config/ftheader.h>
         ^
```
Note how `${FREETYPE_INCLUDE_DIRS}` contains `/Library/Frameworks/Mono.framework/Headers` for some reason.

Adding the absolute path fixes this.

**Comment by rougier** [comment]
Thanks. IT's a bit weird cmake cannot properly locate freetype though. On my OSX system, it seems to work. Do you know if you have other freetype installed that might confuse cmake ?

**Comment by AngeloG** [comment]
The only freetype folder I can see that is probably causing issues is located in Mono: `Library/Frameworks/Mono.framework/Versions/3.12.1/include/freetype2`

**Comment by rougier** [comment]
And is there a `freetype/config/ftheader.h`inside ?

**Comment by AngeloG** [comment]
Yes.

**Comment by rougier** [comment]
And what give `freetype-config --cflags`?

**Comment by AngeloG** [comment]
This prints the same as `pkg-config --cflags freetype2`:

`-I/usr/local/Cellar/freetype/2.5.5/include/freetype2`

**Comment by rougier** [comment]
What do you get  from:
```
rm -f CMakeCache.txt
cmake .
```

Also, fro mthe thread you mentionned, it seems the mono framework is interfering. Can you also add
`message(${FREETYPE_INCLUDE_DIRS})` inside you cmake script ?

**Comment by AngeloG** [comment]
The message prints this: `/Library/Frameworks/Mono.framework/Headers/usr/local/include/freetype2`

This is the complete output:
```
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework
-- Found GLUT: /System/Library/Frameworks/GLUT.framework
-- Found Freetype: /usr/local/lib/libfreetype.dylib (found version "2.5.5")
/Library/Frameworks/Mono.framework/Headers/usr/local/include/freetype2
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28")
-- Found Fontconfig: /usr/local/Cellar/fontconfig/2.11.1/lib/libfontconfig.dylib
-- Found AntTweakBar: /usr/local/include
-- Found Libstdc++ needed by atb-agg.c .
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/angel/dev/freetype-gl
```

Note that this is not on the latest commit, this is the commit just before the glfw3 port, because otherwise it complains about glfw3 not being found.

**Comment by rougier** [comment]
Fro the glfw3 "bug", you will have to do:

```
ln -s /usr/local/cmake/glfw /usr/local/cmake/glfw3
```

It is a known bug from glfw from what I've understood.

**Comment by rougier** [comment]
Can you force the freetype dir using ccmake (expert mode) ?

**Comment by AngeloG** [comment]
I saw that comment, but that folder doesn't exist for me. `ln: /usr/local/cmake/glfw3: No such file or directory`

**Comment by rougier** [comment]
Ah damn. Did you install it using homebrew ? glfw or glfw3 ?

**Comment by AngeloG** [comment]
It's worth noting that `FONTCONFIG_INCLUDE_DIR` is set to `/Library/Frameworks/Mono.framework/Headers/fontconfig`.

Also, `FREETYPE_INCLUDE_DIR_freetype2` is already set to `/usr/local/include/freetype2` while `FREETYPE_INCLUDE_DIR_ft2build` is set to the Mono directory.

Changing the latter to `/usr/local/include/freetype2` makes it build.

**Comment by AngeloG** [comment]
glfw3 is installed via brew:

```
glfw3: stable 3.1.1 (bottled)
http://www.glfw.org/
/usr/local/Cellar/glfw3/3.1.1 (11 files, 260K) *
  Built from source
From: https://github.com/homebrew/homebrew-versions/blob/master/glfw3.rb
```

**Comment by rougier** [comment]
In my `/usr/local/lib/cmake`, I have:

```
lrwxr-xr-x    1 rougier  staff     39 May  1 09:11 glfw@ -> ../../Cellar/glfw3/3.1.1/lib/cmake/glfw
lrwxr-xr-x    1 rougier  staff      4 Aug 20 07:56 glfw3@ -> glfw
```

But I do not know where the glfw actually comes from (from brew installation or if added the link myself)

**Comment by AngeloG** [comment]
Aha, you wrote `/usr/local/cmake` instead of `/usr/local/lib/cmake`. This worked:

`ln -s /usr/local/lib/cmake/glfw /usr/local/lib/cmake/glfw3`

Also, I think the issue can be closed. In conclusion, you can fix this by using `ccmake` and setting `FREETYPE_INCLUDE_DIR_ft2build` to the proper directory.

**Comment by rougier** [comment]
Maybe it's worth writing an INSTALL.txt just to add a specific section for OSX.
