### ISSUE TITLE
glfw3 not found

### ISSUE THREAD

**Issue by chaosink** [rougier/freetype-gl#78]
CMake Error at CMakeLists.txt:78 (FIND_PACKAGE):
  By not providing "Findglfw3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glfw3", but
  CMake did not find one.

  Could not find a package configuration file provided by "glfw3" with any of
  the following names:

    glfw3Config.cmake
    glfw3-config.cmake

  Add the installation prefix of "glfw3" to CMAKE_PREFIX_PATH or set
  "glfw3_DIR" to a directory containing one of the above files.  If "glfw3"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by chaosink** [comment]
I have already installed glfw3.

**Comment by rougier** [comment]
Can you try:
```
ln -s /usr/local/lib/cmake/glfw /usr/local/lib/cmake/glfw3
```

**Comment by chaosink** [comment]
Yes, it works! Thank you so much!
I'm not familiar with cmake. It seems that I should spend some time on it.

**Comment by rougier** [comment]
I get the exact same bug actually... (not too familiar with cmake either)
