### ISSUE TITLE
Compiling instructions?

### ISSUE THREAD

**Issue by StrikerMan780** [rougier/freetype-gl#82]
Are there any compiling instructions anywhere? I've been ripping my hair out trying to figure everything out. I've tried using CMake, but it produces an .sln that won't compile.

**Comment by rougier** [comment]
The procedure is:
```
cmake .
make
```

Does it work for you ?

**Comment by StrikerMan780** [comment]
I can't use make since I'm not using MinGW. I did use CMake to compile an SLN file, which mostly worked except cmake didn't properly set the directories for GLFW.

**Comment by rougier** [comment]
It depends on what you intend to do with freetype-gl. The philosophy is to take the part you want to put them in your project.

**Comment by StrikerMan780** [comment]
That doesn't really tell me anything. I tried copying the headers over, and I got pounded with a ton of unresolved external symbol errors, even when I included freetype itself and the freetype-gl.lib file.

**Comment by rougier** [comment]
If you're ready to do some experiments, we can try to sort this out and write a USE.txt file.
Can you post a short summary of the missing symbols ?

**Comment by StrikerMan780** [comment]
It'll be a few minutes, I had removed everything from my project. I gotta put it back in.

**Comment by StrikerMan780** [comment]
```
Severity	Code	Description	Project	File	Line
Error	LNK1120	27 unresolved externals	tfury	H:\sourcecode\TerminalFury\TerminalFury\test\tfury.exe	1
Error	LNK2019	unresolved external symbol _FT_Done_Face referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Done_FreeType referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Done_Glyph referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Get_Char_Index referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Get_Glyph referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Get_Kerning referenced in function _texture_font_generate_kerning	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Glyph_Stroke referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Glyph_StrokeBorder referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Glyph_To_Bitmap referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Init_FreeType referenced in function _texture_font_load_face	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Library_SetLcdFilter referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Library_SetLcdFilterWeights referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Load_Glyph referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_New_Face referenced in function _texture_font_load_face	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_New_Memory_Face referenced in function _texture_font_load_face	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Select_Charmap referenced in function _texture_font_load_face	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Set_Char_Size referenced in function _texture_font_load_face	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Set_Transform referenced in function _texture_font_load_face	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Stroker_Done referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Stroker_New referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol _FT_Stroker_Set referenced in function _texture_font_load_glyphs	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2019	unresolved external symbol __except_handler4_common referenced in function __except_handler4	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\MSVCRTD.lib(_chandler4gs_.obj)	1
Error	LNK2019	unresolved external symbol __imp__realloc referenced in function _vector_reserve	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(vector.obj)	1
Error	LNK2019	unresolved external symbol __imp__round referenced in function _texture_font_init	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2001	unresolved external symbol __imp__strdup	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\OLDNAMES.lib(strdup.obi)	1
Error	LNK2019	unresolved external symbol __imp__strdup referenced in function _texture_font_new_from_file	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2001	unresolved external symbol __imp___strdup	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\OLDNAMES.lib(strdup.obi)	1
Error	LNK2001	unresolved external symbol __imp___wassert	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-font.obj)	1
Error	LNK2001	unresolved external symbol __imp___wassert	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(vector.obj)	1
Error	LNK2019	unresolved external symbol __imp___wassert referenced in function _texture_atlas_new	tfury	H:\sourcecode\TerminalFury\TerminalFury\core\freetype-gl.lib(texture-atlas.obj)	1

```

**Comment by StrikerMan780** [comment]
To make things even more confusing, freetype-gl.lib isn't in terminalfury\core\, it's in terminalfury\lib\freetype-gl\

**Comment by rougier** [comment]
All the _FT_ are related to the Freetype library (which is mandatory).
For the round and strdup, they are define in plaform.c/platform.h

Here is a list of files, the ticked ones are needed.

* [ ] CMakeCache.txt
* [ ] CMakeFiles
* [ ] CMakeLists.txt
* [ ] CMakeModules
* [ ] LICENSE
* [ ] Makefile
* [ ] README.md
* [ ] TODO
* [ ] cmake_install.cmake
* [ ] data
* [ ] demos
* [ ] doc
* [ ] edtaa3func.c
* [ ] edtaa3func.h
* [ ] font-manager.c
* [ ] font-manager.h
* [ ] fonts
* [ ] freetype-gl.h
* [ ] harfbuzz
* [ ] libfreetype-gl.a
* [ ] makefont
* [ ] makefont.c
* [ ] markup.h
* [ ] mat4.c
* [ ] mat4.h
* [ ] opengl.h
* [ ] platform.c
* [ ] platform.h
* [ ] shader.c
* [ ] shader.h
* [ ] shaders
* [ ] text-buffer.c
* [ ] text-buffer.h
* [ ] texture-atlas.c
* [ ] texture-atlas.h
* [ ] texture-font.c
* [ ] texture-font.h
* [ ] vec234.h
* [ ] vector.c
* [ ] vector.h
* [ ] vertex-attribute.c
* [ ] vertex-attribute.h
* [ ] vertex-buffer.c
* [ ] vertex-buffer.h
* [ ] windows

**Comment by StrikerMan780** [comment]
Here's my new folder:

http://puu.sh/ktQIY/5664e8fd45.png

is this right? Don't I need the windows folder too?

**Comment by rougier** [comment]
If you're on windows, you'll need the windows directory as well (I've no access to and no experience with windows). Someone else can probably give some help.

**Comment by StrikerMan780** [comment]
Never used windows before?

**Comment by rougier** [comment]
Only a long long time ago...

**Comment by StrikerMan780** [comment]
Ah, is there someone else who works on this that you could perhaps refer to me that does know?

**Comment by rougier** [comment]
Maybe @cforfang can help.

**Comment by cforfang** [comment]
I set up a stand-alone VS2015 project using freetypegl as a library [here](https://github.com/cforfang/freetypegl-example). Does looking at that as a refrence help you at all?

The main points of interest are (under configuration properties):
* VC++ Directories
  * Include Directories
  * Library Directories
* Linker
  * Additional Dependencies
* Debugging
  * Working Directory

To build freetypegl.lib I set up CMake(-gui) as follows:
![0001-cmake](https://cloud.githubusercontent.com/assets/544178/10215283/83b0aa16-6820-11e5-81b4-68884940dafa.png)

I also had to build GLFW and Freetype from source as the Win32 binaries on the website and in this project respectively doesn't seem to work with VS2015.

**Comment by StrikerMan780** [comment]
I fixed it last night by doing something similar to what you described, except I also set the project to "Multi-Threaded" instead of "Multi-Threaded DLL".

**Comment by gameengineer** [comment]
Thank you cforfang for showing your cmake screenshot.  A fresh download and running CMake selecting VS2013 was failing to Configure. Checking GLFW_SUPPLIED and _LIBS_SUPPLIED at least allowed the Configuration and Generation to work.  However like most everybody there were a host of compiler errors.  Now to fix the host of errors.  I only really care about outline fonts and the freetype-gl library (obviously) anyway so to save me from headaches I'll just copy over the projects and files I want by hand.

**Comment by cirosantilli** [comment]
On Ubuntu 15.10, you can't get more precise than https://github.com/rougier/freetype-gl/blob/a4cfb9abac19a0ab62b625a9b6f856e032fe3732/.travis.yml

In particular, you have to:

- compile ant tweak bar from source https://github.com/rougier/freetype-gl/issues/112 There is no Ubuntu package, and that project is marked as unmaintained. There isn't even a `make install` target AFAIK, you have to `mv`! we should fork that project, or replace it with some of http://gamedev.stackexchange.com/questions/3617/good-gui-for-opengl
- compile GLFW from source because of a Debian packaging bug: https://github.com/rougier/freetype-gl/issues/94#issuecomment-215968624
- apply the upstream patch https://github.com/rougier/freetype-gl/blob/a4cfb9abac19a0ab62b625a9b6f856e032fe3732/.travis.yml#L23 , the `mv` and the `sed` cannot be skipped.

**Comment by adrianbroher** [comment]
The workaround for this Issue is now documented in INSTALL.md.  Closing this issue as fixed.
