### ISSUE TITLE
Outline color?

### ISSUE THREAD

**Issue by StrikerMan780** [rougier/freetype-gl#83]
I've looked through the documentation, but I cannot find the means of setting the outline color. The outline demo just shows a white outline, but I need to know how to control the outline color separate from the text color. (Aiming for solid white text with a black outline.)

Something like this: ![logo](http://new1.fjcdn.com/comments/4400724+_c8555bdd7fdadb9b9a311837fabce567.png)

**Comment by rougier** [comment]
Have a look at cartoon demo.

**Comment by StrikerMan780** [comment]
I'm... not sure what I should be looking for.

**Comment by rougier** [comment]
Exactly. You can also use SDF and craft a shader to draw the outline in different color.
Have a look at: https://www.safaribooksonline.com/library/view/iphone-3d-programming/9781449388133/ch07s03.html
