### ISSUE TITLE
Circular dependecies in CMake ?

### ISSUE THREAD

**Issue by rougier** [rougier/freetype-gl#88]
When compiling, I now get:

```
...
[ 61%] Built target distance-field-3
make[2]: *** No rule to make target `demos/makefont', needed by `demos/vera-16.h'.  Stop.
make[1]: *** [demos/CMakeFiles/generate-embedded-font.dir/all] Error 2
make: *** [all] Error 2
```

and makefont is not yet build, any idea ?

**Comment by adrianbroher** [comment]
Did you try to remove the build and run cmake again?

**Comment by rougier** [comment]
Yes, a lot of time. Do you already have the vera-16.h file in your demos directory when you build from scratch ?

**Comment by adrianbroher** [comment]
No, I deleted the whole build directory and recreated it so there can't be any 'vera-16.h' file.  But the

> target `demos/makefont'

is a bit suspicious.  The makefont target and executable are located in the root directory, not in the 'demos' subdirectory.

**Comment by rougier** [comment]
Also, it might be a good idea to have a dedicated src directory.

Not connected, but previously I was using
```
mkdir build
cd build
cmake ..
```

But now this leaves the build directory empty. Is there something wrong with my cmake install ?

**Comment by rougier** [comment]
Ok, it was a cache problem.
