### ISSUE TITLE
Unusued option `freetype-gl_GLFW_SUPPLIED`

### ISSUE THREAD

**Issue by IceDragon200** [rougier/freetype-gl#95]
https://github.com/rougier/freetype-gl/blob/1885e4f02101afda740b960a4cf81dc7d2022728/CMakeLists.txt#L43
```cmake
OPTION(freetype-gl_GLFW_SUPPLIED "GLFW library is supplied as part of parent build" OFF)
```

And then further down
https://github.com/rougier/freetype-gl/blob/1885e4f02101afda740b960a4cf81dc7d2022728/CMakeLists.txt#L80-L82
```cmake
IF ( NOT freetype-gl_LIBS_SUPPLIED )
    FIND_PACKAGE( glfw3 REQUIRED )
ENDIF ( NOT freetype-gl_LIBS_SUPPLIED )
```

So, why does the option exist, if its not used?

**Comment by rougier** [comment]
Good point. Can you make a PR to fix it ?

**Comment by adrianbroher** [comment]
> So, why does the option exist, if its not used?

To be honest: I don't even know why this option exists in the first place.  CMake provides the find_package function, which locates other libraries or applications on the compile host  and sets variables like header directories, library name, link directories, compile flags… .  If the package was already found in the mentioned parent build another call to find_package immediately returns and the variables set by the parent project are used.  So there is no need for this variable anyway.
